In [16]:
import numpy as np
arr=np.array([1,6,2,7,6,4])
x=np.where(arr==6)
print(x)
x=np.wherex1=np.where(arr%2==0)
print(x1)
arr=np.array([0,1,2,2,7,8,9])
x2=np.searchsorted(arr,3,side='lift')
print(x2)
x3=np.searchsorted(arr,8,side='right')
print(x3)
import numpy as np
arr=np.array([0,1,2,2,7,8,9])
x=np.searchsorted(arr,8,side='right')
print(x)

(array([1, 4], dtype=int64),)
(array([0, 2, 3, 5], dtype=int64),)
4
6
6


In [4]:
import numpy as np
arr=np.array([9,5,2,7,6,4])
print(np.sort(arr))

[2 4 5 6 7 9]


In [6]:
arr=np.array([[7,4,9],[9,1,4]])
print(np.sort(arr))

[[4 7 9]
 [1 4 9]]


In [9]:
import numpy as np
arr=np.array([31,78,68,88])
x=[False,True,True,False]
newarr=arr[x]
print(x)
print(newarr)

[False, True, True, False]
[78 68]


In [11]:
arr=np.array([31,78,68,88])
filter_arr=arr>70
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)

[False  True False  True]
[78 88]
