In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
slice1=arr[2:6]
print(slice1)

[3 4 5 6]


In [2]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
subarray=arr[0:2,1:3]
print(subarray)

[[2 3]
 [5 6]]


In [3]:
col1=arr[:,0]
print(col1)

[1 4 7]


In [5]:
row1=arr[0,:]
print(row1)

[1 2 3]


In [6]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0:3:2])
print(arr[0::2])
print(arr[1::])
print(arr[0,1:3])
print(arr[2:,2:])
print(arr[:,2])

[[1 2 3]
 [7 8 9]]
[[1 2 3]
 [7 8 9]]
[[4 5 6]
 [7 8 9]]
[2 3]
[[9]]
[3 6 9]


In [7]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[0])
print(arr[4])
print(arr[-1])
print(arr[1:4])
print(arr[arr>25])
print(arr[[1,3]])

10
50
50
[20 30 40]
[30 40 50]
[20 40]


In [8]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0,0])
print(arr[1,2])

1
6


In [10]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.hstack((arr1,arr2))
print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [11]:
result1=np.vstack((arr1,arr2))
print(result1)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [12]:
result2=np.dstack((arr1,arr2))
print(result2)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [13]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
result=np.split(arr,3)
print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [14]:
arr=np.array([1,2,3,4,5])
result=np.split(arr,3)
print(result)

ValueError: array split does not result in an equal division

In [15]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
result=np.hsplit(arr,3)
print(result)

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [16]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
result=np.vsplit(arr,3)
print(result)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [17]:
arr=np.array([[[1,2],[3,4],[5,6],[7,8]]])
result=np.dsplit(arr,2)
print(result)

[array([[[1],
        [3],
        [5],
        [7]]]), array([[[2],
        [4],
        [6],
        [8]]])]
